/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'milko.mitropolitsky' at '10/17/16 9:01 PM' with Gradle 2.14.1
 *
 * @author milko.mitropolitsky, @date 10/17/16 9:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
